name: OIDC to Power BI API

on:
  push:
    branches: [main]

jobs:
  call-powerbi-api:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read

    steps:
      - name: Authenticate to Azure using OIDC
        id: az_login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Access Token for Power BI
        id: get_token
        run: |
          ACCESS_TOKEN=$(az account get-access-token \
            --resource=https://analysis.windows.net/powerbi/api \
            --query accessToken -o tsv)
          echo "::add-mask::$ACCESS_TOKEN"
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT

      - name: Call Power BI API
        run: |
          curl -H "Authorization: Bearer ${{ steps.get_token.outputs.access_token }}" \
            https://api.powerbi.com/v1.0/myorg/datasets
