name: OIDC to Power BI API

on:
  push:
    branches: [main]

jobs:
  call-powerbi-api:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Get OIDC token from GitHub
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken();
            core.setOutput("id_token", token);

      - name: Debug OIDC token
        run: |
          echo "${{ steps.oidc.outputs.id_token }}" > token.jwt

          IFS='.' read -r HEADER PAYLOAD SIGNATURE < token.jwt

          echo "----- HEADER -----"
          echo "$HEADER" | base64 -d | jq .

          echo "----- PAYLOAD -----"
          echo "$PAYLOAD" | base64 -d | jq .

      - name: Exchange OIDC token for access token
        id: token
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -d "grant_type=client_credentials" \
            -d "scope=https://analysis.windows.net/powerbi/api/.default" \
            -d "client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer" \
            -d "client_assertion=${{ steps.oidc.outputs.id_token }}" \
            "https://login.microsoftonline.com/${{ secrets.AZURE_TENANT_ID }}/oauth2/v2.0/token")

          echo "RESPONSE=$RESPONSE"
          echo "access_token=$(echo $RESPONSE | jq -r '.access_token')" >> $GITHUB_OUTPUT
          echo "Access token length: $(echo $RESPONSE | jq -r '.access_token' | wc -c)"

      - name: Call Power BI API
        run: |
          echo "Calling Power BI API..."
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ steps.token.outputs.access_token }}" \
               https://api.powerbi.com/v1.0/myorg/groups/9f398c76-be07-426b-958d-063cbafa2c1b/datasets)

          echo "Power BI API response:"
          echo "$RESPONSE" | jq .
